### ISSUE TITLE
Sub-menu with list of paired vehicles

### ISSUE THREAD

**Issue by yksen** [copilot-app/copilot#18]
```[tasklist]
### Tasks
- [x] Design the layout of sub-menu
- [x] Menu accessible by holding down on the dashboard icon in bottom navigation
- [x] Something to inform the user of menu's existence like a plus icon
```

**Comment by yksen** [comment]
https://developer.android.com/reference/android/widget/PopupMenu
https://www.geeksforgeeks.org/popup-menu-in-android-with-example/

Perhaps a customized version of this?
